# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAITranslation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
