# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAITranslation', '0002_auto_20161215_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='translatedText',
            field=models.TextField(blank=True),
        ),
    ]
