# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAITranslation', '0003_auto_20161216_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='suggestedAnswer',
            field=models.TextField(blank=True),
        ),
    ]
